defaults:
  - base

_target_: src.model.NeuralPBM
name: Neural PBM
loss:
  _target_: src.loss.BinaryCrossEntropy
optimizer: adam
learning_rate: 0.0001
position_bias: 1.0
layers: [32]
dropouts: [0]
activation:
  _target_: torch.nn.ELU
