name: ultr-cm-vs-ips
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.7.1
  - torchvision=0.8.2
  - jupyterlab=3.4.4
  - gcc=12.1.0
  - pip=21.2.4
  - altair_saver=0.5.0
  - altair=3.3.0
  - hydra-core=1.2.0
  - pandas=1.4.1
  - numpy=1.21.5
  - scikit-learn=1.0.2
  - pip:
      - hydra_submitit_launcher==1.2.0
      - pytorch_lightning==1.6.5
      - pytorchltr==0.2.1
      - pyarrow==4.0.1
      - lightgbm==3.3.2
      - wget==3.2
