_target_: src.baseline.LightGBMRanker
name: LightGBM
objective: lambdarank
boosting_type: gbdt # LambdaMART = LambdaRank + Gradient Boosted Decision Trees
metric: ndcg
n_estimators: 100
n_leaves: 31
learning_rate: 0.1
early_stopping_patience: 10
random_state: "${random_state}"
