defaults:
  - _self_
  - data: mslr30k
  - baseline: lgbm
  - simulation: graded-pbm

experiment:
  name: default

hydra:
  job:
    chdir: True
  output_subdir: .
  run:
    dir: results/${experiment.name}
  sweep:
    dir: results/${experiment.name}
    subdir: ${hydra.job.override_dirname}
