defaults:
  - _self_
  - data: yahoo
  - baseline: lgbm
  - simulation: graded-pbm
  - model: cm

experiment:
  name: default

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 100
  accelerator: auto
  callbacks:
    -
     _target_: pytorch_lightning.callbacks.EarlyStopping
     monitor: val_loss
     patience: 5

train_loader:
  _target_: torch.utils.data.DataLoader
  dataset: ???
  batch_size: 50
  shuffle: true

val_test_loader:
  _target_: torch.utils.data.DataLoader
  dataset: ???
  batch_size: 500
  shuffle: false


hydra:
  job:
    chdir: True
  output_subdir: .
  run:
    dir: results/${experiment.name}
  sweep:
    dir: results/${experiment.name}
    subdir: ${hydra.job.override_dirname}
